# Generated by Django 5.1.15 on 2026-09-05 18:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StormEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('basin', models.CharField(choices=[('BOB', 'Bay of Bengal'), ('AS', 'Arabian Sea'), ('SP', 'South Pacific'), ('SI', 'South Indian Ocean')], default='BOB', max_length=8)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CycloneShelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('state', models.CharField(db_index=True, max_length=128)),
                ('district', models.CharField(db_index=True, max_length=128)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('capacity', models.IntegerField(default=0)),
                ('shelter_type', models.CharField(default='MPCS', max_length=64)),
                ('data_source', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'district'], name='cyclones_cy_state_0188c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SatelliteObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('center_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('estimated_msw', models.FloatField(help_text='Maximum Sustained Wind in Knots')),
                ('imd_category', models.CharField(max_length=64)),
                ('basin_category', models.CharField(blank=True, default='', max_length=64)),
                ('satellite_source', models.CharField(default='INSAT-3D/3DS', max_length=64)),
                ('storm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='cyclones.stormevent')),
            ],
        ),
    ]
